definitions:
  config.Config:
    properties:
      environment:
        type: string
      httphost:
        type: string
      httpport:
        type: string
      postgresDatabase:
        type: string
      postgresHost:
        type: string
      postgresPassword:
        type: string
      postgresPort:
        type: string
      postgresUser:
        type: string
    type: object
  views.R:
    properties:
      data:
        type: object
      error_code:
        example: 0
        type: integer
      error_note:
        example: Error Note
        type: string
      status:
        example: Success | Failure
        type: string
    type: object
host: localhost:7070
info:
  contact:
    email: sodikjon.akhmedoff@gmail.com
    name: s-akhmedoff
    url: https://github.com/s-akhmedoff
  description: This is a sample server
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  title: Simple Service REST API
  version: "1.0"
paths:
  /config:
    get:
      description: expose all configs for debugging
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            environment:
              description: Current environment
              type: string
            go-os:
              description: Go OS
              type: string
            go-version:
              description: Version of Golang
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/views.R'
            - properties:
                data:
                  $ref: '#/definitions/config.Config'
              type: object
        "405":
          description: Method Not Allowed
          headers:
            environment:
              description: Current environment
              type: string
            go-os:
              description: Go OS
              type: string
            go-version:
              description: Version of Golang
              type: string
          schema:
            $ref: '#/definitions/views.R'
      summary: Show config
swagger: "2.0"
