version: '3.8'

services:
  postgres:
    container_name: postgresql
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - default

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - default

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - redis_volume:/var/lib/redis
    ports:
      - 6379:6379
    networks:
      - default

  simple:
    depends_on:
      - postgres
      - rabbitmq
    image: sadakhmedoff/simple-repo/microservice/simple-service/simple:latest
    restart: always
    env_file:
      - .env
    ports:
      - "7070:7070"

volumes:
  prometheus_volume:
  grafana_volume:
  postgres_volume:
  pgadmin_volume:
  rabbitmq_volume:
  redis_volume:

networks:
  default:
