version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbit_mq
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
      - rabbit_etc:/etc/rabbitmq/
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_logs:/var/log/rabbitmq/
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  simple:
    image: sadakhmedoff/simple-repo/microservice/simple-service/simple:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - HTTP_PORT=:7072
      - SERVER_IP=${SERVER_IP}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=dbo_productcatalog
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "7072:7072"

volumes:
  postgres_data:
  rabbit_etc:
  rabbit_data:
  rabbit_logs: