version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbit_mq
    image: rabbitmq:3-management-alpine
    restart: always
    volumes:
      - rabbit_etc:/etc/rabbitmq/
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_logs:/var/log/rabbitmq/
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  simple:
    depends_on:
      - postgres
      - rabbitmq
    image: sadakhmedoff/simple-repo/microservice/simple-service/simple:latest
    environment:
      - HTTP_PORT=:7070
      - SERVER_IP=${SERVER_IP}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=simple_db
      - RMQ_URL=${RMQ_URL}
      - RMQ_EXCHANGE_NAME=${RMQ_EXCHANGE_NAME}
      - RMQ_ROUTING_KEY=${RMQ_ROUTING_KEY}
    ports:
      - "7070:7070"

volumes:
  postgres_data:
  rabbit_etc:
  rabbit_data:
  rabbit_logs: